### ISSUE TITLE
Install Failing on High Sierra

### ISSUE THREAD

**Issue by Dylan-M** [exaile/homebrew-exaile#1]
Install always fails for me on High Sierra. I'm not super up on Python, and I'm not sure what the next steps would be to debug. So, looking for a little guidance and assistance in getting this running.

```
$ brew install exaile/exaile/exaile
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
latexdiff                                                                                   libsigc++

==> Installing exaile from exaile/exaile
==> Downloading https://github.com/exaile/exaile/releases/download/4.0.0-rc3/exaile-4.0.0rc3.tar.gz
Already downloaded: /Users/dylanmyers/Library/Caches/Homebrew/downloads/8f5c8f35f7cbe7f78626c9df681c458f56abddee6892a45a1f0ceb39966cdb3c--exaile-4.0.0rc3.tar.gz
==> Downloading https://files.pythonhosted.org/packages/33/bc/fa0b5347139cd9564f0d44ebd2b147ac97c36b2403943dbee8a25fd74012/virtualenv-16.0.0.tar.gz
Already downloaded: /Users/dylanmyers/Library/Caches/Homebrew/downloads/02e9f856894cc3f1979f2bf31e2f709c30ef64ea80ce14a80cc83e384528d06f--virtualenv-16.0.0.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/private/tmp/exaile--homebrew-virtualenv-20181031-48993-ecz0d4/target --install-scripts=/private/tmp/exaile--homebrew
==> python -s /private/tmp/exaile--homebrew-virtualenv-20181031-48993-ecz0d4/target/bin/virtualenv -p python /usr/local/Cellar/exaile/4.0.0rc3/libexec
==> Downloading https://files.pythonhosted.org/packages/a9/f3/d8d1f8d998436256b3abcd924570d54f9508fa313c4e27bfa663f1bb72f2/bsddb3-5.3.0.tar.gz
Already downloaded: /Users/dylanmyers/Library/Caches/Homebrew/downloads/ab8475492573a41773d223feee67e229726992868feac0bd3756123cb8be6d76--bsddb3-5.3.0.tar.gz
==> /usr/local/Cellar/exaile/4.0.0rc3/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/exaile--bsddb3-20181031-48993-1o18g9p/bsddb3-5.3.0
==> Downloading https://files.pythonhosted.org/packages/91/d8/7d37fec71ff7c9dbcdd80d2b48bcdd86d6af502156fc93846fb0102cb2c4/feedparser-5.2.1.tar.bz2
Already downloaded: /Users/dylanmyers/Library/Caches/Homebrew/downloads/4d88c849f974860ade94aabb94c4f4eac55723cfc548d69a7631275cae85d6e2--feedparser-5.2.1.tar.bz2
==> /usr/local/Cellar/exaile/4.0.0rc3/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/exaile--feedparser-20181031-48993-1tqatbd/feedparser-5.2.1
==> Downloading https://files.pythonhosted.org/packages/63/cc/67ad422295750e2b9ee57c27370dc85d5b85af2454afe7077df6b93d5938/musicbrainzngs-0.6.tar.gz
Already downloaded: /Users/dylanmyers/Library/Caches/Homebrew/downloads/d0037ecf1dcdce34afeb52335e00377f69d787915afd04323c77f06e057d547b--musicbrainzngs-0.6.tar.gz
==> /usr/local/Cellar/exaile/4.0.0rc3/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/exaile--musicbrainzngs-20181031-48993-vl93t/musicbrainzngs
==> Downloading https://files.pythonhosted.org/packages/2c/6a/0b2caf9364db074b616b1b8c26ce7166a883c21b0e40bd50f6db02307afe/mutagen-1.40.0.tar.gz
Already downloaded: /Users/dylanmyers/Library/Caches/Homebrew/downloads/738547dfb8dee7ddfed993556611bdc767ae3bfb2e0f950cc95f1b50dbb23e51--mutagen-1.40.0.tar.gz
==> /usr/local/Cellar/exaile/4.0.0rc3/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/exaile--mutagen-20181031-48993-7s6zn3/mutagen-1.40.0
==> Downloading https://files.pythonhosted.org/packages/64/ab/973b67a9dfd27d6356c5e275d7d369b35879fe88bda6e1b20453b4d08511/pylast-1.8.0.tar.gz
Already downloaded: /Users/dylanmyers/Library/Caches/Homebrew/downloads/f45ac88bd731461a8e5ea5966320efe39862a0a99cdb6c431578d07d7ca5e51b--pylast-1.8.0.tar.gz
==> /usr/local/Cellar/exaile/4.0.0rc3/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/exaile--pylast-20181031-48993-avvgju/pylast-1.8.0
==> Downloading https://files.pythonhosted.org/packages/16/d8/bc6316cf98419719bd59c91742194c111b6f2e85abac88e496adefaf7afe/six-1.11.0.tar.gz
Already downloaded: /Users/dylanmyers/Library/Caches/Homebrew/downloads/39b8c00e9e4ed8a443e08812ff5c07dbf9eded0b8626003f72c26bf3caeaa6b1--six-1.11.0.tar.gz
==> /usr/local/Cellar/exaile/4.0.0rc3/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/exaile--six-20181031-48993-h1kr5d/six-1.11.0
==> Downloading https://files.pythonhosted.org/packages/7e/03/303a5c7f7c3d3af811eba44b32ef957e570be4d5c5b656c0b44ece6191e0/pyobjc-core-3.2.1.tar.gz
Already downloaded: /Users/dylanmyers/Library/Caches/Homebrew/downloads/93793375fd8f53c287aa79364205f2d3f12718667f54b44f406487a116e235a5--pyobjc-core-3.2.1.tar.gz
==> /usr/local/Cellar/exaile/4.0.0rc3/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/exaile--pyobjc-core-20181031-48993-1c8uedg/pyobjc-core-3.2
==> Downloading https://files.pythonhosted.org/packages/a1/8d/77c2b2741865a4781ae8f52e5cd802b728e705f3c7fa017e9a7866ad999e/pyobjc-framework-ApplicationServices-3.2.1.tar.gz
Already downloaded: /Users/dylanmyers/Library/Caches/Homebrew/downloads/279600baeb9a8e889580a46f01a1ce1b2ec0a16b202be6d3c51e45f425a6bab8--pyobjc-framework-ApplicationServices-3.2.1.tar.gz
==> /usr/local/Cellar/exaile/4.0.0rc3/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/exaile--pyobjc-framework-ApplicationServices-20181031-4899
==> Downloading https://files.pythonhosted.org/packages/f2/91/9a1847a442a8cd9f7e7ed183561c57b8644fd582f7ede0c5c3dc81407533/pyobjc-framework-Cocoa-3.2.1.tar.gz
Already downloaded: /Users/dylanmyers/Library/Caches/Homebrew/downloads/9081e7d8607f9ea7327be50717907e15f64a25e43b57437b3b56cb8956d10ba9--pyobjc-framework-Cocoa-3.2.1.tar.gz
==> /usr/local/Cellar/exaile/4.0.0rc3/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/exaile--pyobjc-framework-Cocoa-20181031-48993-r3u25r/pyobj
Last 15 lines from /Users/dylanmyers/Library/Logs/Homebrew/exaile/11.pip:
Removed build tracker '/private/tmp/pip-req-tracker-WXoy6i'
Command "/usr/local/Cellar/exaile/4.0.0rc3/libexec/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-req-build-1shj1P/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-h5S9E6/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/exaile/4.0.0rc3/libexec/bin/../include/site/python2.7/pyobjc-framework-Cocoa" failed with error code 1 in /private/tmp/pip-req-build-1shj1P/
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/exaile/4.0.0rc3/libexec/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/exaile/4.0.0rc3/libexec/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 366, in run
    use_user_site=options.use_user_site,
  File "/usr/local/Cellar/exaile/4.0.0rc3/libexec/lib/python2.7/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/usr/local/Cellar/exaile/4.0.0rc3/libexec/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 791, in install
    spinner=spinner,
  File "/usr/local/Cellar/exaile/4.0.0rc3/libexec/lib/python2.7/site-packages/pip/_internal/utils/misc.py", line 705, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "/usr/local/Cellar/exaile/4.0.0rc3/libexec/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-req-build-1shj1P/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-h5S9E6/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/exaile/4.0.0rc3/libexec/bin/../include/site/python2.7/pyobjc-framework-Cocoa" failed with error code 1 in /private/tmp/pip-req-build-1shj1P/

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/exaile/homebrew-exaile/issues
```

**Comment by virtuald** [comment]
Hm, unfortunately my mac is still on Sierra, and I'm not able to update at this time.

It seems that the older version of pyobjc doesn't compile on high sierra -- but I know I had issues compiling the newer version on Sierra, so maybe there's a way to select a particular version based on which OS is being installed? It would be the following lines that would need to be updated to the newest version:

* https://github.com/exaile/homebrew-exaile/blob/318455efdc7e8181fe8645b9f883dfaa5cd82cb5/Formula/exaile.rb#L54
* https://github.com/exaile/homebrew-exaile/blob/318455efdc7e8181fe8645b9f883dfaa5cd82cb5/Formula/exaile.rb#L59
* https://github.com/exaile/homebrew-exaile/blob/318455efdc7e8181fe8645b9f883dfaa5cd82cb5/Formula/exaile.rb#L64
* https://github.com/exaile/homebrew-exaile/blob/318455efdc7e8181fe8645b9f883dfaa5cd82cb5/Formula/exaile.rb#L69

**Comment by virtuald** [comment]
Hey @Dylan-M I finally got my upgrade, so I played with this for a bit. Determined that the problem was that a user needed to have the entirety of xcode installed, which seems a bit much. Instead, I hacked it to install the distributed wheels from pypi, and that seems to work on my 10.14 system.

If you haven't already moved on, I'd love to know if this works for you!

**Comment by Dylan-M** [comment]
I'm no longer with that company, thus I no longer have a Mac to play around on. If I end up with one at a future place of employment I'll definitely give this a try again. Thanks.

**Comment by luksak** [comment]
I am still facing this issue on macOS 10.14.6:

```
$ brew install exaile/exaile/exaile
==> Installing exaile from exaile/exaile
==> Downloading https://github.com/exaile/exaile/releases/download/4.0.0/exaile-
Already downloaded: /Users/lukasvonblarer/Library/Caches/Homebrew/downloads/2284b5a946b835f5c4b7727f8f56d82ce4e4d65c825959a61711370e3a7f3b35--exaile-4.0.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/11/74/2c151a13ef41ab9fb4
Already downloaded: /Users/lukasvonblarer/Library/Caches/Homebrew/downloads/507d2087bf24df82641b681a5fe4da778ef50ebe819a86ea1b584f70788f0f63--virtualenv-16.7.4.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/private/tmp/e
Last 15 lines from /Users/lukasvonblarer/Library/Logs/Homebrew/exaile/01.python:
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/private/tmp/exaile--homebrew-virtualenv-20191007-61389-ufqtjw/target
--install-scripts=/private/tmp/exaile--homebrew-virtualenv-20191007-61389-ufqtjw/target/bin
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named setuptools

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/exaile/homebrew-exaile/issues
```

**Comment by virtuald** [comment]
That's a slightly different issue, it seems that setuptools isn't installed. I suppose we could add setuptools as a dependency, but I figured that would just come with virtualenv et al? It seems like python 3 would solve this, but homebrew seems to be undecided for python 2.

**Comment by luksak** [comment]
Alright, sorry for that. I created a separate issue for that: #2
